version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database

    #entrypoint: "bash -c './wait-for-it.sh $${databse:5432} -t 60 -- java -jar td-0.0.1.SNAPSHOT.jar'"

  database:
    image: postgres:14
    environment:
        - POSTGRES_PASSWORD=dev_password
        - POSTGRES_USER=si5_sacc
        - POSTGRES_DB=td_1
        - POSTGRES_URL=jdbc:postgresql://database:5432/db